version: '{build}'

branches:
  only:
  - master

image:
- Visual Studio 2019

configuration:
- Debug
- Release

environment:
  matrix:
  # Comilers matrix
  - env_cmake_generator: "Visual Studio 16 2019"
    env_cmake_architecture: Win32
  - env_cmake_generator: "Visual Studio 16 2019"
    env_cmake_architecture: x64

build_script:
  - mkdir build_cmake
  - pushd build_cmake
  - cmake -G "%env_cmake_generator%" -A %env_cmake_architecture% -S ".." -DCMAKE_BUILD_TYPE=%configuration% -DGRAPHICS_EXAMPLES_BUILD:BOOL=TRUE -DGRAPHICS_TESTS:BOOL=TRUE
  - cmake --build . --config %configuration%
  - ctest --output-on-failure -C %configuration%
  - popd