version: '{build}'

branches:
  only:
  - master

image:
- Visual Studio 2019

configuration:
- Debug
- Release

environment:
  matrix:
  # Comilers matrix
  - env_cmake_generator: "Visual Studio 16 2019"
    env_cmake_architecture: Win32
  - env_cmake_generator: "Visual Studio 16 2019"
    env_cmake_architecture: x64

build_script:
  - mkdir build_cmake
  - pushd build_cmake
  - cmake -G "%env_cmake_generator%" -A %env_cmake_architecture% -S ".." -DCMAKE_CONFIGURATION_TYPES=%configuration% -DGRAPHICS_EXAMPLES_BUILD:BOOL=FALSE -DGRAPHICS_TESTS:BOOL=TRUE
  - cmake --build .
  - ctest --output-on-failure
  - popd